// All user-facing copy of the card designer, in the four site languages.
// Kept inside the editor folder so the module can be shared with the app.
import { l } from "./locale";

export const s = {
  from: l("from", "ab", "dès", "da"),
  // Step / section headings
  stepCard: l("Card", "Karte", "Carte", "Carta"),
  stepDesign: l("Design", "Design", "Design", "Design"),
  stepTemplate: l("Template", "Vorlage", "Modèle", "Modello"),
  stepLogo: l("Your logo", "Ihr Logo", "Votre logo", "Il tuo logo"),
  stepColors: l("Colours", "Farben", "Couleurs", "Colori"),
  stepContent: l("Content", "Inhalt", "Contenu", "Contenuto"),
  stepLink: l("Destination", "Ziel", "Destination", "Destinazione"),
  stepOrder: l("Order", "Bestellung", "Commande", "Ordine"),
  // Wizard navigation
  stepWord: l("Step", "Schritt", "Étape", "Passo"),
  back: l("Back", "Zurück", "Retour", "Indietro"),
  continue: l("Continue", "Weiter", "Continuer", "Continua"),
  // Card-type step
  cardTypeHint: l(
    "Pick the card you want, then design its face in the next steps.",
    "Wählen Sie die gewünschte Karte, gestalten Sie die Vorderseite in den nächsten Schritten.",
    "Choisissez la carte souhaitée, puis personnalisez sa face dans les étapes suivantes.",
    "Scegli la carta che vuoi, poi personalizza il fronte nei passaggi successivi.",
  ),
  finishLabel: l("Finish", "Oberfläche", "Finition", "Finitura"),
  notAvailable: l("Currently not available", "Zurzeit nicht verfügbar", "Actuellement indisponible", "Attualmente non disponibile"),
  // Business-card fields
  stepDetails: l("Your details", "Ihre Angaben", "Vos coordonnées", "I tuoi dati"),
  detailsHint: l(
    "This is what your metal business card shares with one tap.",
    "Das teilt Ihre Metall-Visitenkarte mit einem Tap.",
    "Voici ce que votre carte de visite métal partage d'un tap.",
    "Questo è ciò che il tuo biglietto in metallo condivide con un tap.",
  ),
  fieldName: l("Full name", "Name", "Nom complet", "Nome completo"),
  fieldNamePh: l("Jane Meier", "Jane Meier", "Jane Meier", "Jane Meier"),
  fieldRole: l("Job title", "Position", "Fonction", "Ruolo"),
  fieldRolePh: l("Founder", "Gründerin", "Fondatrice", "Fondatrice"),
  fieldCompany: l("Company", "Firma", "Entreprise", "Azienda"),
  fieldCompanyPh: l("Meier GmbH", "Meier GmbH", "Meier Sàrl", "Meier SA"),
  fieldPhone: l("Phone", "Telefon", "Téléphone", "Telefono"),
  fieldPhonePh: l("+41 79 123 45 67", "+41 79 123 45 67", "+41 79 123 45 67", "+41 79 123 45 67"),
  fieldEmail: l("Email", "E-Mail", "E-mail", "Email"),
  fieldEmailPh: l("jane@meier.ch", "jane@meier.ch", "jane@meier.ch", "jane@meier.ch"),
  fieldWebsite: l("Website", "Website", "Site web", "Sito web"),
  fieldWebsitePh: l("meier.ch", "meier.ch", "meier.ch", "meier.ch"),
  bizNameDefault: l("Your name", "Ihr Name", "Votre nom", "Il tuo nome"),
  // Template picker
  templateHint: l(
    "Start from an industry style and keep everything editable.",
    "Starten Sie mit einem Branchen-Stil, alles bleibt anpassbar.",
    "Partez d'un style sectoriel, tout reste modifiable.",
    "Parti da uno stile di settore, tutto resta modificabile.",
  ),
  presetRestaurant: l("Restaurant", "Restaurant", "Restaurant", "Ristorante"),
  presetElectronics: l("Electronics", "Elektronik", "Électronique", "Elettronica"),
  presetFitness: l("Fitness & Club", "Fitness & Club", "Fitness & Club", "Fitness & Club"),
  presetBeauty: l("Beauty & Salon", "Beauty & Salon", "Beauté & Salon", "Bellezza & Salone"),
  // Logo upload
  uploadLogo: l("Upload your logo", "Logo hochladen", "Téléverser votre logo", "Carica il tuo logo"),
  uploadHint: l(
    "PNG, SVG or JPG. A transparent PNG looks best.",
    "PNG, SVG oder JPG. Ein transparentes PNG wirkt am besten.",
    "PNG, SVG ou JPG. Un PNG transparent est idéal.",
    "PNG, SVG o JPG. Un PNG trasparente rende meglio.",
  ),
  removeLogo: l("Remove logo", "Logo entfernen", "Retirer le logo", "Rimuovi logo"),
  replaceLogo: l("Replace", "Ersetzen", "Remplacer", "Sostituisci"),
  // Colour labels
  colorHeader: l("Header", "Kopfzeile", "En-tête", "Intestazione"),
  colorHeaderText: l("Header text", "Kopftext", "Texte d'en-tête", "Testo intestazione"),
  colorBody: l("Background", "Hintergrund", "Fond", "Sfondo"),
  colorStars: l("Stars", "Sterne", "Étoiles", "Stelle"),
  colorAccent: l("Accent", "Akzent", "Accent", "Accento"),
  // Content fields
  fieldCategory: l("Category label", "Branchen-Label", "Étiquette secteur", "Etichetta categoria"),
  fieldCategoryPh: l("e.g. Fast food & restaurant", "z. B. Schnellrestaurant", "p. ex. Restauration rapide", "es. Ristorazione veloce"),
  fieldHeadline: l("Headline", "Überschrift", "Titre", "Titolo"),
  fieldLogoText: l("Logo label", "Logo-Text", "Texte logo", "Testo logo"),
  fieldLogoHint: l("Logo caption", "Logo-Untertitel", "Légende logo", "Didascalia logo"),
  fontStyle: l("Font style", "Schriftstil", "Style de police", "Stile carattere"),
  fontSans: l("Modern", "Modern", "Moderne", "Moderno"),
  fontSerif: l("Elegant", "Elegant", "Élégant", "Elegante"),
  fontRounded: l("Friendly", "Freundlich", "Convivial", "Amichevole"),
  fontDisplay: l("Bold", "Kräftig", "Impactant", "Deciso"),
  // ── Layout & style section ──────────────────────────────────────
  stepStyle: l("Layout & style", "Layout & Stil", "Mise en page & style", "Layout e stile"),
  styleHint: l(
    "Pick what the card leads with, then fine-tune the look. No big logo? Lead with a message or a short list instead.",
    "Bestimmen Sie, was die Karte in den Mittelpunkt stellt, und verfeinern Sie den Look. Kein grosses Logo? Setzen Sie stattdessen auf eine Botschaft oder eine kurze Liste.",
    "Choisissez l'élément principal de la carte, puis affinez le style. Pas de grand logo ? Misez plutôt sur un message ou une courte liste.",
    "Scegli l'elemento principale della carta, poi rifinisci lo stile. Niente logo grande? Punta invece su un messaggio o un breve elenco.",
  ),
  layoutLabel: l("Layout", "Layout", "Mise en page", "Layout"),
  layoutLogo: l("Logo", "Logo", "Logo", "Logo"),
  layoutLogoHint: l("Big logo in the centre", "Grosses Logo in der Mitte", "Grand logo au centre", "Logo grande al centro"),
  layoutText: l("Message", "Botschaft", "Message", "Messaggio"),
  layoutTextHint: l("A bold custom text", "Ein kräftiger eigener Text", "Un texte fort personnalisé", "Un testo forte personalizzato"),
  layoutList: l("List / menu", "Liste / Menü", "Liste / menu", "Elenco / menù"),
  layoutListHint: l("Menu items or services", "Menüpunkte oder Leistungen", "Plats ou services", "Voci di menù o servizi"),
  headerEdge: l("Header edge", "Kopf-Kante", "Bord d'en-tête", "Bordo intestazione"),
  edgeStraight: l("Straight", "Gerade", "Droit", "Dritto"),
  edgeWave: l("Wave", "Welle", "Vague", "Onda"),
  edgeRound: l("Arch", "Bogen", "Arche", "Arco"),
  edgeScallop: l("Scallop", "Wellenrand", "Feston", "Smerlo"),
  showStars: l("Star rating", "Sterne-Bewertung", "Note en étoiles", "Valutazione a stelle"),
  showStarsHint: l("Show five gold stars in the header", "Fünf goldene Sterne im Kopf anzeigen", "Afficher cinq étoiles dorées dans l'en-tête", "Mostra cinque stelle dorate nell'intestazione"),
  showQr: l("Backup QR code", "Backup-QR-Code", "QR code de secours", "QR code di riserva"),
  showQrHint: l("Add a scannable code for phones without NFC", "Scanbaren Code für Handys ohne NFC hinzufügen", "Ajouter un code scannable pour les téléphones sans NFC", "Aggiungi un codice scansionabile per telefoni senza NFC"),
  // Layout-specific content fields
  fieldBodyText: l("Card message", "Karten-Botschaft", "Message de la carte", "Messaggio della carta"),
  fieldBodyTextPh: l("Loved your visit? Tell the world in 30 seconds.", "Hat es Ihnen gefallen? Erzählen Sie es in 30 Sekunden.", "Vous avez aimé ? Dites-le en 30 secondes.", "Ti è piaciuto? Raccontalo in 30 secondi."),
  fieldListTitle: l("List title", "Listen-Titel", "Titre de la liste", "Titolo elenco"),
  fieldListTitlePh: l("e.g. Today's favourites", "z. B. Beliebt heute", "p. ex. Les favoris du jour", "es. I preferiti di oggi"),
  fieldListItems: l("List items (one per line)", "Listenpunkte (einer pro Zeile)", "Éléments (un par ligne)", "Voci (una per riga)"),
  fieldListItemsPh: l("Signature burger\nHand-cut fries\nHomemade lemonade", "Signature-Burger\nHausgemachte Pommes\nHausgemachte Limonade", "Burger signature\nFrites maison\nLimonade maison", "Burger d'autore\nPatatine fatte in casa\nLimonata fatta in casa"),
  // Destination
  reviewUrl: l("Google review link", "Google-Bewertungslink", "Lien d'avis Google", "Link recensione Google"),
  reviewUrlPh: l("https://g.page/r/…", "https://g.page/r/…", "https://g.page/r/…", "https://g.page/r/…"),
  reviewUrlHint: l(
    "Where a tap sends your customers. Paste your Google review link, or leave it blank and we'll help you set it up.",
    "Wohin ein Tap Ihre Kunden schickt. Fügen Sie Ihren Google-Bewertungslink ein, oder lassen Sie es leer, wir helfen bei der Einrichtung.",
    "Où un tap envoie vos clients. Collez votre lien d'avis Google, ou laissez vide, nous vous aidons à le configurer.",
    "Dove un tap invia i tuoi clienti. Incolla il link di recensione Google, o lascia vuoto, ti aiutiamo a configurarlo.",
  ),
  // Card footer labels (printed on the card)
  cardGoogleReview: l("Google review", "Google-Bewertung", "Avis Google", "Recensione Google"),
  cardTap: l("Tap", "Antippen", "Approcher", "Avvicina"),
  cardPoweredBy: l("Powered by", "Powered by", "Propulsé par", "Powered by"),
  cardSize: l("Card · 120 × 120 mm", "Karte · 120 × 120 mm", "Carte · 120 × 120 mm", "Carta · 120 × 120 mm"),
  cardQrTitle: l("No NFC?", "Kein NFC?", "Pas de NFC ?", "Niente NFC?"),
  cardQrHint: l("Scan to leave a review", "Zum Bewerten scannen", "Scannez pour laisser un avis", "Scansiona per recensire"),
  defaultBodyText: l(
    "Loved your visit? Tap and tell us in 30 seconds.",
    "Hat es Ihnen gefallen? Antippen und in 30 Sekunden erzählen.",
    "Vous avez aimé ? Tapez et dites-le en 30 secondes.",
    "Ti è piaciuto? Tappa e raccontalo in 30 secondi.",
  ),
  defaultListTitle: l("Today's favourites", "Beliebt heute", "Les favoris du jour", "I preferiti di oggi"),
  defaultListItems: l(
    "Signature burger\nHand-cut fries\nHomemade lemonade\nDaily fresh salads",
    "Signature-Burger\nHausgemachte Pommes\nHausgemachte Limonade\nTäglich frische Salate",
    "Burger signature\nFrites maison\nLimonade maison\nSalades fraîches du jour",
    "Burger d'autore\nPatatine fatte in casa\nLimonata fatta in casa\nInsalate fresche del giorno",
  ),
  // Defaults printed on a fresh card
  defaultHeadline: l(
    "We'd love your review!",
    "Wir freuen uns über Ihre Bewertung!",
    "Votre avis nous ferait plaisir !",
    "Ci farebbe piacere una tua recensione!",
  ),
  defaultLogoText: l("YOUR LOGO", "IHR LOGO", "VOTRE LOGO", "IL TUO LOGO"),
  defaultLogoHint: l("Add your logo here", "Firmenlogo hier einfügen", "Ajoutez votre logo ici", "Inserisci qui il tuo logo"),
  // Order panel
  quantity: l("Quantity", "Menge", "Quantité", "Quantità"),
  unitPrice: l("per card", "pro Karte", "par carte", "a carta"),
  total: l("Total", "Total", "Total", "Totale"),
  volumeDiscount: l("Volume discount", "Mengenrabatt", "Remise sur volume", "Sconto quantità"),
  volumeHint: l(
    "The more you order, the less you pay per card.",
    "Je mehr Sie bestellen, desto weniger zahlen Sie pro Karte.",
    "Plus vous commandez, moins vous payez par carte.",
    "Più ordini, meno paghi a carta.",
  ),
  youSave: l("You save", "Sie sparen", "Vous économisez", "Risparmi"),
  orderNote: l(
    "Incl. personalisation & Swiss QA. Free shipping in Switzerland.",
    "Inkl. Personalisierung & Schweizer Qualitätsprüfung. Kostenloser Versand in der Schweiz.",
    "Personnalisation & contrôle qualité suisse inclus. Livraison gratuite en Suisse.",
    "Personalizzazione e controllo qualità svizzero inclusi. Spedizione gratuita in Svizzera.",
  ),
  placeOrder: l("Go to checkout", "Zur Kasse", "Passer à la caisse", "Vai alla cassa"),
  payNow: l("Continue to payment", "Weiter zur Zahlung", "Continuer vers le paiement", "Procedi al pagamento"),
  redirecting: l("Redirecting to payment…", "Weiterleitung zur Zahlung…", "Redirection vers le paiement…", "Reindirizzamento al pagamento…"),
  resetDesign: l("Reset design", "Design zurücksetzen", "Réinitialiser", "Reimposta"),
  estimateNote: l(
    "Prices incl. VAT. The final amount is confirmed on the payment page.",
    "Preise inkl. MWST. Der definitive Betrag wird auf der Zahlungsseite bestätigt.",
    "Prix TVA incluse. Le montant final est confirmé sur la page de paiement.",
    "Prezzi IVA inclusa. L'importo finale viene confermato nella pagina di pagamento.",
  ),
  // Checkout step
  stepCheckout: l("Checkout", "Kasse", "Paiement", "Cassa"),
  checkoutHint: l(
    "Where should we send your cards? You pay securely by card or TWINT on the next page.",
    "Wohin dürfen wir Ihre Karten schicken? Sie bezahlen auf der nächsten Seite sicher per Karte oder TWINT.",
    "Où devons-nous envoyer vos cartes ? Vous payez en toute sécurité par carte ou TWINT à la page suivante.",
    "Dove spediamo le tue carte? Paghi in modo sicuro con carta o TWINT nella pagina successiva.",
  ),
  contactHeading: l("Contact", "Kontakt", "Contact", "Contatto"),
  shippingHeading: l("Shipping address", "Lieferadresse", "Adresse de livraison", "Indirizzo di spedizione"),
  coEmail: l("Email", "E-Mail", "E-mail", "Email"),
  coEmailHint: l(
    "We send your order confirmation here. Use the same address to create your free Taplino account.",
    "Hierhin senden wir Ihre Bestellbestätigung. Mit derselben Adresse erstellen Sie Ihr kostenloses Taplino-Konto.",
    "Nous envoyons la confirmation de commande à cette adresse. Utilisez-la pour créer votre compte Taplino gratuit.",
    "Qui inviamo la conferma d'ordine. Usa lo stesso indirizzo per creare il tuo account Taplino gratuito.",
  ),
  coName: l("Full name", "Vor- und Nachname", "Nom complet", "Nome e cognome"),
  coPhone: l("Phone (optional)", "Telefon (optional)", "Téléphone (facultatif)", "Telefono (facoltativo)"),
  coCompany: l("Company (optional)", "Firma (optional)", "Entreprise (facultatif)", "Azienda (facoltativo)"),
  coLine1: l("Street and number", "Strasse und Nr.", "Rue et numéro", "Via e numero"),
  coLine2: l("Address line 2 (optional)", "Adresszusatz (optional)", "Complément d'adresse (facultatif)", "Indirizzo riga 2 (facoltativo)"),
  coPostalCode: l("Postal code", "PLZ", "NPA", "NPA"),
  coCity: l("City", "Ort", "Localité", "Località"),
  coCountry: l("Country", "Land", "Pays", "Paese"),
  countryCH: l("Switzerland", "Schweiz", "Suisse", "Svizzera"),
  countryLI: l("Liechtenstein", "Liechtenstein", "Liechtenstein", "Liechtenstein"),
  coRequired: l("Required", "Pflichtfeld", "Obligatoire", "Obbligatorio"),
  coInvalidEmail: l(
    "Please enter a valid email address.",
    "Bitte geben Sie eine gültige E-Mail-Adresse ein.",
    "Veuillez saisir une adresse e-mail valide.",
    "Inserisci un indirizzo email valido.",
  ),
  coFixFields: l(
    "Please fill in the highlighted fields.",
    "Bitte füllen Sie die markierten Felder aus.",
    "Veuillez remplir les champs signalés.",
    "Compila i campi evidenziati.",
  ),
  // Notices and errors
  cancelledNotice: l(
    "Payment was cancelled. You can try again whenever you like.",
    "Die Zahlung wurde abgebrochen. Sie können es jederzeit erneut versuchen.",
    "Le paiement a été annulé. Vous pouvez réessayer quand vous le souhaitez.",
    "Il pagamento è stato annullato. Puoi riprovare quando vuoi.",
  ),
  logoTooLarge: l(
    "This SVG is larger than 300 KB. Please simplify it or upload a PNG instead.",
    "Dieses SVG ist grösser als 300 KB. Bitte vereinfachen Sie es oder laden Sie stattdessen ein PNG hoch.",
    "Ce SVG dépasse 300 Ko. Simplifiez-le ou téléversez plutôt un PNG.",
    "Questo SVG supera i 300 KB. Semplificalo o carica invece un PNG.",
  ),
  logoRasterTooLarge: l(
    "This image is too detailed to upload. Please use a simpler logo, ideally a PNG with a transparent background.",
    "Dieses Bild ist zu detailreich. Bitte verwenden Sie ein einfacheres Logo, idealerweise ein PNG mit transparentem Hintergrund.",
    "Cette image est trop détaillée. Utilisez un logo plus simple, idéalement un PNG à fond transparent.",
    "Questa immagine è troppo dettagliata. Usa un logo più semplice, idealmente un PNG con sfondo trasparente.",
  ),
  logoUnreadable: l(
    "We could not read this image. Please try another file.",
    "Dieses Bild konnte nicht gelesen werden. Bitte versuchen Sie eine andere Datei.",
    "Impossible de lire cette image. Essayez un autre fichier.",
    "Impossibile leggere questa immagine. Prova un altro file.",
  ),
  orderError: l(
    "Something went wrong while starting the payment. Please try again in a moment.",
    "Beim Starten der Zahlung ist etwas schiefgelaufen. Bitte versuchen Sie es gleich noch einmal.",
    "Une erreur s'est produite au lancement du paiement. Veuillez réessayer dans un instant.",
    "Qualcosa è andato storto all'avvio del pagamento. Riprova tra un istante.",
  ),
  orderInvalidError: l(
    "Some details were not accepted. Please check your address and design, then try again.",
    "Einige Angaben wurden nicht akzeptiert. Bitte prüfen Sie Adresse und Design und versuchen Sie es erneut.",
    "Certaines informations n'ont pas été acceptées. Vérifiez votre adresse et votre design, puis réessayez.",
    "Alcuni dati non sono stati accettati. Controlla indirizzo e design, poi riprova.",
  ),
  orderStockError: l(
    "There are not enough cards left in stock for this quantity. Lower the quantity or contact us.",
    "Für diese Menge sind nicht mehr genug Karten an Lager. Reduzieren Sie die Menge oder kontaktieren Sie uns.",
    "Il ne reste pas assez de cartes en stock pour cette quantité. Réduisez la quantité ou contactez-nous.",
    "Non ci sono abbastanza carte in magazzino per questa quantità. Riduci la quantità o contattaci.",
  ),
};
